services:
  - type: web
    name: family-bank
    env: elixir
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "_build/prod/rel/family_bank/bin/family_bank start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: family-bank-db
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: PHX_HOST
        value: family-bank.onrender.com
      - key: MIX_ENV
        value: prod
      - key: PHX_SERVER
        value: true
    healthCheckPath: /

databases:
  - name: family-bank-db
    region: oregon
    plan: free